### ISSUE TITLE
problem in build.sbt

### ISSUE THREAD

**Issue by poweihuang17** [ucb-bar/chisel-tutorial#112]
Hi, when I issue " sbt run", it generated this kind of error. But when I changed the type, it's fixed. Is there anyone who's interested to fix this?

My sbt version is 1.1.0.
And my setting in build.sbt  is like this:
name := "chisel-tutorial"
scalaVersion := "2.12.4"
crossScalaVersions := Seq("2.11.11", "2.12.3")

/Users/Powei/Dropbox/riscv/chisel/chisel-tutorial/build.sbt:7: error: scrutinee is incompatible with pattern type;
 found   : Int
 required: Long
      case Some((2, scalaMajor: Int)) if scalaMajor < 12 => Seq()
                                ^
/Users/Powei/Dropbox/riscv/chisel/chisel-tutorial/build.sbt:19: error: scrutinee is incompatible with pattern type;
 found   : Int
 required: Long
      case Some((2, scalaMajor: Int)) if scalaMajor < 12 =>

Thanks in advance.

**Comment by poweihuang17** [comment]
I fix it by changing the type from Int to Long.

**Comment by ucbjrl** [comment]
The release branches of chisel-template and chisel-tutorial use sbt 0.13. When we switch to sbt 1.0 and Scala 2.12 (which will probably happen within a month) for all the chisel-related repos, we'll update these as well.

**Comment by ucbjrl** [comment]
Closed by #123
