### ISSUE TITLE
sbt run get error

### ISSUE THREAD

**Issue by botaichang** [ucb-bar/chisel-tutorial#144]
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.2.5.
[warn]  [FAILED     ] org.scala-sbt#compiler-bridge_2.12;1.2.5!compiler-bridge_2.12.jar(src): java.lang.NullPointerException (178ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#util-interface;1.2.2: java.lang.NullPointerException
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] The compiler bridge sources org.scala-sbt:compiler-bridge_2.12:1.2.5:compile could not be retrieved.
[error]
[error]         Note: Unresolved dependencies path:
[error]                 org.scala-sbt:util-interface:1.2.2
[error]                   +- org.scala-sbt:compiler-interface:1.2.5
[error]                   +- org.scala-sbt:compiler-bridge_2.12:1.2.5

**Comment by hattonl** [comment]
using a faster and stable software to download scientifically

**Comment by botaichang** [comment]
> using a faster and stable software to download scientifically

thanks a lot and i have already run it successfully.
