### ISSUE TITLE
Probably typos in the Wiki?

### ISSUE THREAD

**Issue by schoeberl** [ucb-bar/chisel-tutorial#96]
There are several words in the Wiki formatted as follows: *abc*+. I assume the plus has no meaning is is some translation/typo mistake. If this is the case I can fix them when reading along.

**Comment by ucbjrl** [comment]
I believe these are all gone. Is it time to close this issue?

**Comment by schoeberl** [comment]
Still see some. E.g. I edited now following to remove "from an n+ bit wide value is n-1+”

https://github.com/ucb-bar/chisel-tutorial/wiki/basic-types-and-operations

But ok to close. As I know those are simply typos I can just fix them when stumbling over them.

Cheers,
Martin

**Comment by schoeberl** [comment]
Fixed some. Time to close.
